### ISSUE TITLE
Kanban board set-up

### ISSUE THREAD

**Issue by Kakalanp** [yersel500/catalog_my_things#5]
- [Here is our GitHub project](https://github.com/yersel500/catalog_my_things/projects/1)

- We're a group of three (3) people:
  - @yersel500  As team member N°1
  - @Kakalanp  As team member N°2
  - @Thi-Ponce  As team member N°3

**Comment by VICTOR-CHUKWU** [comment]
Hi Team, 
## CHANGES REQUIRED

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

- [x] I can not see any task assigned to the group, kindly add the group task as a card to the Kanban board

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Kakalanp** [comment]
### We added three of them:

- #30
- #31
- #32

**Comment by elisha2kyakpo1** [comment]
Hi 👋 team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
